---
title: "Final Grade Reflection"
author: "Jun Noh"
format: pdf
editor: visual
---

In this document, you make a data-based argument for the grade you've earned in this course. Your argument should include evidence from the supporting artifacts you've provided.

## The output document should be a PDF or a Word Document, as it should be a **maximum** of 2-pages.

I believe I have earned an A in this class because I have been able to meet every learning target, challenge myself to make better documents/code, and have contributed to being a good classmate. In lab 4 #1 I met targets WD-1 and R-1. Target WD-6 was shown in lab 4 #9 and WD-4, WD-7, PE-4 in lab 4 #10. WD-3, PE-4 was shown in lab 4 \# 4. DVS-2 was in lab 5 #3 along with DVS-1 which was shown in lab 5 #4, 5, 6. DSM-2 was found in lab 9 #2, 3, 4. WD-5 was located in preview activity 4 #4-6. DVS-4 was in lab 9 #1 along with PE-1 which was found in lab 9 #1a. DVS-6 and DVS-7 can both be found in challenge 9 #5. DVS-5 was found in lab 7 #2 along with R-3, PE-2 in lab 7 #4 and #8. R-3 can also be found in lab 3 #10. Lab 3 #9 contains WD-2. PE-3 was found in Lab 8 #2 and 6. DSM-1 is in practice activity 9 #4 and 4a. DVS-3 was in challenge 4 #3 as well as lab 4 #11, and lab 5 #6. I think throughout these examples I have shown learning target R-2 by using tidy code and making my labs/challenges reproducible.

Other than learning targets I have achieved throughout the class, I have also shown commitment to continued learning and extended thinking. Throughout the challenges I have tried to add unique elements such as challenge 2 option 3 where I used annotations or challenge 4 #3 where I scaled my graph. I chose challenges 2 and 4 because I thought I displayed creativity and skills beyond what was needed such as using annotations or scaling graphs to make them look less skewed. I also think these graphs looked professional for the tools we were given at the time and am proud because it showed my improvement in understanding data visualization. Challenge 9 is another place I think I went beyond the standards that were needed. I used html formatting from previous experience to center my table titles because I believed that made them look clearer than having it left adjusted. I also changed the font into something more standard. Additionally, I have consistently been doing revisions when given the chance and try to not to repeat those mistakes in future projects.

As a team member and classmate, I think I have grown more comfortable working as a team member throughout the quarter, I am able to share my ideas and also talk through others' suggestions. I am not hesitant to reach out to my group members for help, and I also try to share things I have found useful that might also help them. Furthermore, I try to come to class with my preview activities completed, so that I am not behind during the practice activity. Along with the fact that I complete preview activities before class and show up to every class I have also answered a few questions on discord. I think these two factors have shown that I contribute to a good classroom environment.

Finally, I have met my personal goals that I had set earlier in the year. I am more comfortable working with R and using the tools within R to accomplish various tasks, I also find working in a group to be easier now which is another goal I had initially set at the start of the year. My biggest achievement I have met throughout the year though was probably learning how to make better visualizations that would reflect the dataset I was working with. I feel that I have improved dramatically in the way I envision graphs not only in a statistical sense, but also in aspects such as efficient titles, scaling, and making the graphs more readable. In this sense, I am very proud of what I have accomplished throughout the quarter and especially proud that I was able to reach my personal goals set out at the start of the quarter.
