---
title: "Practice Activity 9"
author: "Jun Noh"
format: html
editor: visual
---

## Loading in

```{r}
library(tidyverse)
library(broom)
library(here)
```

## 1. Regression

```{r}
animals <- read_csv(here::here("supporting_artifacts", "Learning Targets", "Practice_Activity_9", "mystery_animal.csv"))
```

## 2. Fitting

```{r}
animals_lm<- animals |> 
  lm(weight_after ~ weight_before, data = _)
```

```{r}
augment(animals_lm)
```

## 3. Plotting

```{r}
animals_lm |> 
  augment() |> 
  ggplot(mapping = aes(y = .resid, x = weight_before)) +
    geom_point()
```

## 4. Simulation

```{r}
qunif(0.95, min = 1.5, max =3.5)
qnorm(0.1, mean = 4.6, sd = 0.8)
pnorm(5, mean = 4.6, sd = 0.8, lower.tail = FALSE)
pchisq(5, df = 4, lower.tail = FALSE)

random <- rnorm(100, 4.6, 0.8)
```

## 4a.

```{r}
music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones, cornets, reeds))
  
}

set.seed(1957)

my_weights <- rerun(.n = 1000, 
                    music_man(n_tromb = 76, 110, 1035)
                    ) |> 
  flatten_dbl()

my_weights <- as.data.frame(my_weights)


```

## 4b. 

```{r}
my_weights |> 
  filter(my_weights < 4532)
```
