---
title: "Challenge 9"
author: "Jun Noh"
execute: 
  error: true
format: 
  html:
    self-contained: true
    toc: true
    toc-location: left
    code-fold: true
editor: visual
---

## Loading in libraries/dataset

```{r}
#| message: false 
#| warning: false
library(tidyverse)
library(here)
library(broom)
library(knitr)
library(kableExtra)
library(DT)
library(scales)
```

```{r}
#| message: false
babyNames <- read_csv(here::here("supporting_artifacts", "Extended Thinking", 
                                 "Challenge 9", "StateNames_A.csv")) |> 
  rename(Sex = "Gender")
```

## 1. Interactive dataset for babyNames

```{r}
#| message: false
#| warning: false
datatable(babyNames)
```

## 2a. **Summarizing & Visualizing the Number of Allisons - All**

```{r}
#| message: false
babyNames |> 
  group_by(Sex, State) |> 
  filter(Name == "Allison") |> 
  summarize(Total = sum(Count)) |>
  pivot_wider(names_from = Sex, values_from = Total) |> 
  mutate(M = replace_na(M, 0), `F` = replace_na(`F`, 0)) |> 
  kable(caption = "<center><strong>Frequencies of babies named 
        Allison by state</strong></center>") |> 
  kable_styling(bootstrap_options = "striped", html_font = "Cambria") 
```

## **2b. Summarizing & Visualizing the Number of Allisons - Female**

```{r}
#| message: false
babyNames |> 
  mutate(Count = replace_na(Count, 0)) |> 
  group_by(Sex, State) |> 
  filter(Name == "Allison", Sex == "F") |> 
  summarize(Total = sum(Count)) |>
  kable(caption = "<center><strong>Frequencies of female babies named 
        Allison by state</strong></center>") |> 
  kable_styling(bootstrap_options = "striped", html_font = "Cambria") 
```

## 3. Alan dataset

```{r}
A_names <- babyNames |> 
  filter(Name %in% c("Alan", "Allen", "Allan"), Sex == "M")
```

## 4. Interactive dataset for A_names

```{r}
datatable(A_names)
```

## 5. Total Counts

```{r}
#| message: false
A_names |> 
  filter(State %in% c("CA", "PA"), Year == "2000") |> 
  pivot_wider(names_from = Name, values_from = Count) |> 
  mutate(across(Alan:Allan, .fns = replace_na, 0)) |> 
  rowwise() |> 
  mutate(Total = sum(Alan, Allen, Allan)) |> 
  select(-c(Year, Sex)) |> 
  kable(caption = "<center><strong>Total counts of Different Alan 
        spellings in CA and PA in 2000</strong></center>") |> 
  kable_styling(bootstrap_options = "striped", html_font = "Cambria") 
  
```

## 6. Percentages

```{r}
#| message: false
A_names |> 
  filter(State %in% c("CA", "PA"), Year == "2000") |> 
  pivot_wider(names_from = Name, values_from = Count) |> 
  mutate(across(Alan:Allan, .fns = replace_na, 0)) |> 
  rowwise() |> 
  mutate(total = sum(Alan, Allen, Allan), Alan = percent(Alan/total), 
         Allen = percent(Allen/total), 
         Allan = percent(Allan/total)) |> 
  select(-c(total, Year, Sex)) |> 
  kable(caption = "<count><strong>Percentages of different Alan 
        spellings in CA and PA in 2000 rounded 
        to nearest whole number</strong></center>", 
        digits = 2) |> 
  kable_styling(bootstrap_options = "striped", html_font = "Cambria") 
```
