---
title: "Preview Activity 4"
author: "jun noh"
format: 
  html:
    self-contained: true
    code-fold: true
editor: visual
---

## Set up

```{r}
#| message: false
library(tidyverse)
library(here)
```

## 1. Loading in data

```{r}
#| message: false
cereal <- read_csv(here::here("supporting_artifacts", "Learning Targets", "Preview_Activity_4", "cereal.csv"))
```

## 2. Pivoting

```{r}
cereals_long <- cereal |> 
  select(name, protein, fat, fiber) |> 
  pivot_longer(cols = c('protein', 'fat', 'fiber'), names_to = 'Nutrient', values_to = 'Amount')
```

## 3. joining data

```{r}
prof_info <- data.frame(
  professor = 
    c("Bodwin", "Glanz", "Carlton", "Sun", "Theobold"),
  undergrad_school = 
    c("Harvard", "Cal Poly", "Berkeley", "Harvard", "Colorado Mesa University"),
  grad_school = 
    c("UNC", "Boston University", "UCLA", "Stanford", "Montana State University")
)

prof_course <- data.frame(
  professor = c("Bodwin", "Glanz", "Carlton", "Theobold"),
  Stat_331 = c(TRUE, TRUE, TRUE, TRUE),
  Stat_330 = c(FALSE, TRUE, TRUE, FALSE),
  Stat_431 = c(TRUE, TRUE, FALSE, TRUE)
)

course_info <- data.frame(
  course = c("Stat_331", "Stat_330", "Stat_431"),
  num_sections = c(8, 3, 1)
)
```

## 4. combining a and b

```{r}
prof_info |> 
  inner_join(prof_course, by = 'professor')
```

## 5. combining a and b

```{r}
prof_info |> 
  full_join(prof_course, by = 'professor')
```

## 6. combining b and c

```{r}
prof_course |> 
  pivot_longer(cols = c('Stat_331', 'Stat_330', 'Stat_431'), names_to = 'course', values_to = 'can_teach') |> 
  inner_join(course_info, by = 'course')
```
