---
title: "The Power of Efficiency"
format: html
editor: visual
---

## The power of efficiency

I believe the definition of efficiency in regards to data science/statistical computing is limiting the use of repetitive lines of code and using tools such as functions or iteration to get rid of certain cases of repetition. Other aspects of efficiency in statistical computing include using modern/updated tools and using the simplest code/tools possible to finish a job. I like to think of efficiency as jobs carried out with fewer lines of code is better and also refraining from repeating yourself by creating functions or intermediate objects. Efficiency allows data scientists to save time on writing long lines of code because they are able to use simpler tools, it also allows your code to be more readable and reproducible since others would be less confused if your lines of code are clear and well written. Efficiency also allows people to get tasks done quickly and require less work on the machine and the data scientist themselves. I encountered efficiency the most when creating functions or intermediate objects to pipe into ggplot or other functions. Lab 9 #1a showed the usage of efficiency and also served as an aha moment towards why efficiency is so useful. I realized that I was piping these few lines of code into a lot of other functions therefore I decided to create an intermediate object instead to avoid multiple copy pasting and longer lines of code. Lab 8 #1, 2, and 6 also served as a reminder why iterations and functions are much better when writing efficient code. Functions and iterations are meant to prevent us from using the same lines of code multiple times and it served this purpose for the lab, otherwise this lab may have been a lot longer in terms of code. Overall, I think throughout the course the two biggest aha moments I had when it came to efficiency was trying to limit the amount of times a code chunk is repeated through the usage of intermediate objects, functions, or iterations in order to save more time and space. I think a good rule of thumb I learned was if the code chunk is being repeated more than twice one of the methods mentioned above should be used rather than copy and pasting the same code chunk multiple times.
